### ISSUE TITLE
Filter by Route weight

### ISSUE THREAD

**Issue by zlatent** [tomasonjo/grand-sigmaJS#1]
Is it feasible to only return the routes with `weight` above a certain threshold?

https://github.com/tomasonjo/grand-sigmaJS/blob/e34ef5acd4acf536c3fa1bbcec5ee934a0c9c580/ui/src/components/SigmaRootForceAtlas.js#L26

thanks!

**Comment by tomasonjo** [comment]
yes you can use the following query:

```
query AllRoutes {
    airports {
      name
      pagerank
      louvain
      fullName
      country
      outgoing_routesConnection (where: {edge: {weight_GT: 2.0}}) {
        edges {
          weight
          node {
            name
          }
        }
      }
    }
  }
```

When you have the project running, open localhost:4000 to open Apollo playground and you can check available options

**Comment by zlatent** [comment]
it works like a charm, thanks very much! is it possible to exclude isolated nodes, i.e., airports without any route with weight > 2.0?
